apiVersion: v1
kind: Service
metadata:
  name: random-number
  labels:
    app: random-number
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: random-number
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: random-number-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: random-number
        version: v1
    spec:
      containers:
      - name: random-number
        image: uday1bhanu/random-number:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 10m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 50Mi
---
##########################################################################
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: random-number
          servicePort: 3000
---
##########################################################################
apiVersion: v1
items:
- apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    name: random-number-v1
    namespace: default
  spec:
    maxReplicas: 4
    minReplicas: 1
    scaleTargetRef:
      apiVersion: extensions/v1beta1
      kind: Deployment
      name: random-number-v1
    targetCPUUtilizationPercentage: 80
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""